# Practice 2: US Online Directory - yelp

In this practice exercise, we will analyse a yelp dataset. Yelp is a popular online directory for discovering local businesses ranging from bars, restaurants, and cafes to hairdressers, spas, and gas stations. Use the Yelp_data.csv perform tasks and answer the following questions:

Importing pandas with the alias pd.

In [2]:
#Wrtie your code here
import pandas as pd

Load dataset to a dataframe called df_yelp

In [6]:
#Wrtie your code here
df_yelp = pd.read_csv ('Data\Yelp_data.csv')

Display 5 first record of dataframe

In [7]:
#Wrtie your code here
df_yelp.head()

,Unnamed: 0,business_id,city,full_address,latitude,longitude,name,review_count,stars,state,...,Pakistani,Barbeque,Vietnamese,Asian Fusion,Diners,Greek,Vegetarian,Number_of_Checkins,Number_of_Tips,Number_of_Tip_Likes
0,0,5UmKMjUEUNdYWqANhGckJw,Dravosburg,"4734 Lebanon Church Rd Dravosburg, PA 15034",40.354327,-79.900706,Mr Hoagie,4,4.5,PA,...,0,0,0,0,0,0,0,0,0,0
1,1,UsFtqoBl7naz8AVUBZMjQQ,Dravosburg,"202 McClure St Dravosburg, PA 15034",40.350553,-79.886814,Clancy's Pub,4,3.5,PA,...,0,0,0,0,0,0,0,0,0,0
2,2,3eu6MEFlq2Dg7bQh8QbdOg,Dravosburg,"1 Ravine St Dravosburg, PA 15034",40.350956,-79.889059,Joe Cislo's Auto,3,5.0,PA,...,0,0,0,0,0,0,0,0,0,0
3,3,cE27W9VPgO88Qxe4ol6y_g,Bethel Park,"1530 Hamilton Rd Bethel Park, PA 15234",40.354115,-80.014660,Cool Springs Golf Center,5,2.5,PA,...,0,0,0,0,0,0,0,9,1,0
4,4,HZdLhv6COCleJMo7nPl-RA,Pittsburgh,"301 South Hills Village Pittsburgh, PA 15241",40.357620,-80.059980,Verizon,5,2.5,PA,...,0,0,0,0,0,0,0,0,0,0

Find the average star rating for each state (You can ignore the number of reviews for each restaurant). Store the result in df_1 variable

In [10]:
#Wrtie your code here
df = df_yelp.groupby('state')
df['stars'].mean()

state
AL     3.500000
AR     5.000000
AZ     3.709510
BW     3.768531
CA     3.500000
EDH    3.807777
ELN    3.791667
FIF    3.700000
HAM    4.500000
IL     3.549728
KHL    3.500000
MA     5.000000
MLN    3.842466
MN     5.000000
NC     3.587095
NM     3.000000
NTH    2.000000
NV     3.682979
NW     4.500000
ON     3.577825
OR     2.500000
PA     3.699276
QC     3.579906
RP     4.083333
SC     3.568266
SCB    4.000000
TX     4.500000
WI     3.659335
Name: stars, dtype: float64

For each state compute the avg number of stars and review_count they got.

In [11]:
#Wrtie your code here
df[['review_count','stars']].mean()

       review_count     stars
state
AL         4.000000  3.500000
AR        23.000000  5.000000
AZ        27.845296  3.709510
BW        11.759441  3.768531
CA        42.000000  3.500000
EDH       12.305416  3.807777
ELN        4.916667  3.791667
FIF        7.800000  3.700000
HAM        3.000000  4.500000
IL        23.532698  3.549728
KHL        8.000000  3.500000
MA         3.000000  5.000000
MLN        8.787671  3.842466
MN         4.000000  5.000000
NC        23.475803  3.587095
NM        14.000000  3.000000
NTH       17.000000  2.000000
NV        49.552060  3.682979
NW         6.000000  4.500000
ON        11.068230  3.577825
OR         9.000000  2.500000
PA        26.593139  3.699276
QC         8.944771  3.579906
RP         5.500000  4.083333
SC        14.734317  3.568266
SCB        5.666667  4.000000
TX       501.000000  4.500000
WI        23.033262  3.659335

Find the business that have review_count more than 500 reviews for Arizona(AZ) state

Solution 1

In [14]:
#Wrtie your code here
az_df = df.get_group('AZ')
az_df[az_df['review_count'] > 500]

,Unnamed: 0,business_id,city,full_address,latitude,longitude,name,review_count,stars,state,...,Pakistani,Barbeque,Vietnamese,Asian Fusion,Diners,Greek,Vegetarian,Number_of_Checkins,Number_of_Tips,Number_of_Tip_Likes
2401,2401,qMkIbQFrROSnPaQ7at85-w,Phoenix,"1201 N Galvin Pkwy Phoenix, AZ 85008",33.462167,-111.944971,Desert Botanical Garden,522,4.5,AZ,...,0,0,0,0,0,0,0,1961,121,1
2609,2609,AkOruz5CrCxUmXe1p_WoRg,Phoenix,"914 E Camelback Rd Phoenix, AZ 85014",33.509529,-112.060958,Cherryblossom Noodle Cafe,683,4.0,AZ,...,0,0,0,1,0,0,0,2510,195,1
3103,3103,R8VwdLyvsp9iybNqRvm94g,Phoenix,"4410 N 40th St Phoenix, AZ 85018",33.502313,-111.995752,La Grande Orange Grocery,651,4.0,AZ,...,0,0,0,0,0,0,0,4631,276,3
3110,3110,SDwYQ6eSu1htn8vHWv128g,Phoenix,"3939 E Campbell Ave Phoenix, AZ 85018",33.502111,-111.996339,Postino Arcadia,1087,4.5,AZ,...,0,0,0,0,0,0,0,3469,221,0
3949,3949,hW0Ne_HTHEAgGF1rAdmR-g,Phoenix,"3400 E Sky Harbor Blvd Phoenix, AZ 85034",33.435717,-112.006717,Phoenix Sky Harbor International Airport - PHX,1786,3.5,AZ,...,0,0,0,0,0,0,0,68711,1963,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59857,59858,z-vuSxK4jQvRBdsk4lFCAw,Scottsdale,"11055 N Scottsdale Rd Scottsdale, AZ 85254",33.586835,-111.925891,Hopdoddy Burger Bar,547,4.0,AZ,...,0,0,0,0,0,0,0,1559,91,3
60933,60934,7Q19H5nM3oFRyCg_j0QV1A,Gilbert,"721 N Arizona Ave Gilbert, AZ 85233",33.363016,-111.841114,Arizona Wilderness Brewing,537,4.0,AZ,...,0,0,0,0,0,0,0,2688,125,3
62604,62605,Je396Ev-dvAvl3ei-O0EIg,Mesa,"2740 S Alma School Rd Ste 13 Mesa, AZ 85210",33.364927,-111.860568,Angry Crab Shack,567,4.0,AZ,...,0,0,0,0,0,0,0,1309,100,2
62794,62795,guLkdetJ603Bw_A6tuecIg,Phoenix,"4455 E Camelback Rd Phoenix, AZ 85018",33.509105,-111.984514,The Henry,522,4.0,AZ,...,0,0,0,0,0,0,0,2042,72,1
63546,63547,GmzpzmxinfLMw5OXQKFEBQ,Phoenix,"4301 E University Dr Phoenix, AZ 85034",33.421587,-111.989088,Little Miss BBQ,667,5.0,AZ,...,0,1,0,0,0,0,0,994,113,3

-----------------------------End of Practice ---------------------------------------------------------